---
abstract: 'Communicate with an MPD server'
author:
  - 'Alan Berndt <alan@eatabrick.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.023
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MPD
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/bentglasstube/Net-MPD/issues
  homepage: https://github.com/bentglasstube/Net-MPD
  repository: https://github.com/bentglasstube/Net-MPD.git
version: 0.01
