---
abstract: 'Communicate with an MPD server'
author:
  - 'Alan Berndt <alan@eatabrick.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MPD
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: 0
  IO::Socket::INET: 0
  Scalar::Util: 0
  perl: 5.010
  version: 0.77
resources:
  bugtracker: https://github.com/bentglasstube/Net-MPD/issues
  homepage: https://github.com/bentglasstube/Net-MPD
  repository: https://github.com/bentglasstube/Net-MPD.git
version: 0.05
